version: '2'
services:
  web:
    image: web
    command: ["/start.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:9.3
    volumes:
      - .:/db
