version: '2'
services:
  web:
    image: web
    command: bash -c "python3 manage.py runserver -h 0.0.0.0 -p 8080"
#    command: ["/start.sh"]
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:9.3
