version: '2'
services:
  web:
    image: web
    command: python3 manage.py runserver -h 0.0.0.0 -p 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:9.3
    ports:
     - "5433:5432"
    volumes:
     - .:/db
